# region imports
from AlgorithmImports import *
# endregion

# ═══════════════════════════════════════════════════════════════════════════════
# HDD LOCKED PARAMETERS - DO NOT SWEEP
# ───────────────────────────────────────────────────────────────────────────────
# Trial: {{TRIAL_NUMBER}} of 5 | Hypothesis: {{HYPOTHESIS_ID}}
# Single Change This Trial: {{SINGLE_CHANGE}}
# Fail Condition: {{FAIL_CONDITION}}
# ═══════════════════════════════════════════════════════════════════════════════


class EventDrivenStrategy(QCAlgorithm):
    """
    Strategy Type: Event Driven
    Template for earnings, news, and catalyst strategies.
    Generated by: strategy-builder agent
    """

    def initialize(self) -> None:
        self.set_start_date(2020, 1, 1)
        self.set_cash(100000)

        # === Universe ===
        self.symbols = []
        for ticker in {{SYMBOLS}}:
            equity = self.add_equity(ticker, Resolution.DAILY)
            self.symbols.append(equity.symbol)

        # === Event Tracking ===
        # HDD LOCKED: Do NOT sweep indicator periods
        self.pending_events = {}
        self.positions = {}

        # === Risk Parameters ===
        # HDD LOCKED: Risk parameter - requires new hypothesis to change
        self.risk_per_trade = 0.01
        self.max_hold_days = 3

        # === Regime Detection ===
        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.sma200 = self.sma(self.spy, 200)
        self.regime_multiplier = 1.0  # Default, updated in on_data

    def on_data(self, data: Slice) -> None:
        self._update_regime_multiplier()

        for symbol in self.symbols:
            if not self.portfolio[symbol].invested:
                if self._event_signal(symbol, data):
                    self._execute_entry(symbol, data)
            else:
                if self._exit_signal(symbol, data):
                    self._execute_exit(symbol, data)

    def _update_regime_multiplier(self) -> None:
        """Update position size multiplier based on market regime."""
        if not self.sma200.is_ready:
            self.regime_multiplier = 0.5  # Conservative when unknown
            return

        spy_price = self.securities[self.spy].price
        above_200dma = spy_price > self.sma200.current.value

        # {{REGIME_CONDITIONS}} - User-specified regime logic
        if above_200dma:
            self.regime_multiplier = 1.0  # Full size in uptrend
        else:
            self.regime_multiplier = 0.5  # Half size in downtrend

    def _event_signal(self, symbol, data: Slice) -> bool:
        """Check for event-driven signal. {{EVENT_CONDITIONS}}"""
        # {{EVENT_SIGNAL_LOGIC}} - User-specified event detection
        # Example: earnings surprise, news sentiment, etc.
        return False  # Placeholder - implement based on strategy

    def _exit_signal(self, symbol, data: Slice) -> bool:
        """Time-based exit for event strategies"""
        if symbol in self.positions:
            days_held = (self.time - self.positions[symbol]).days
            return days_held >= self.max_hold_days
        return False

    def _execute_entry(self, symbol, data: Slice) -> None:
        price = data[symbol].close
        risk_dollars = self.portfolio.total_portfolio_value * self.risk_per_trade
        stop_distance = price * 0.05  # 5% event volatility assumption
        base_shares = int(risk_dollars / stop_distance)
        shares = int(base_shares * self.regime_multiplier)

        if shares > 0:
            self.market_order(symbol, shares)
            self.positions[symbol] = self.time

    def _execute_exit(self, symbol, data: Slice) -> None:
        self.liquidate(symbol)
        self.positions.pop(symbol, None)
