# region imports
from AlgorithmImports import *
# endregion

# ═══════════════════════════════════════════════════════════════════════════════
# HDD LOCKED PARAMETERS - DO NOT SWEEP
# ───────────────────────────────────────────────────────────────────────────────
# Trial: {{TRIAL_NUMBER}} of 5 | Hypothesis: {{HYPOTHESIS_ID}}
# Single Change This Trial: {{SINGLE_CHANGE}}
# Fail Condition: {{FAIL_CONDITION}}
# ═══════════════════════════════════════════════════════════════════════════════


class MeanReversionStrategy(QCAlgorithm):
    """
    Strategy Type: Mean Reversion
    Template for oversold bounce and regression strategies.
    Generated by: strategy-builder agent
    """

    def initialize(self) -> None:
        self.set_start_date(2020, 1, 1)
        self.set_cash(100000)

        # === Universe ===
        self.symbols = []
        for ticker in {{SYMBOLS}}:
            self.symbols.append(self.add_equity(ticker, Resolution.DAILY).symbol)

        # === Indicators (Mean Reversion) ===
        # HDD LOCKED: Do NOT sweep indicator periods
        self.indicators = {}
        for symbol in self.symbols:
            self.indicators[symbol] = {
                "rsi": self.rsi(symbol, 14),
                "bb": self.bb(symbol, 20, 2),
                "sma": self.sma(symbol, 20),
            }

        # === Risk Parameters ===
        # HDD LOCKED: Risk parameter - requires new hypothesis to change
        self.risk_per_trade = 0.01
        self.max_hold_bars = 5
        self.entry_bar = {}

        # === Regime Detection ===
        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.sma200 = self.sma(self.spy, 200)
        self.regime_multiplier = 1.0  # Default, updated in on_data

    def on_data(self, data: Slice) -> None:
        self._update_regime_multiplier()

        for symbol in self.symbols:
            if not self._indicators_ready(symbol):
                continue

            if not self.portfolio[symbol].invested:
                if self._entry_signal(symbol, data):
                    self._execute_entry(symbol, data)
            else:
                if self._exit_signal(symbol, data):
                    self._execute_exit(symbol, data)

    def _indicators_ready(self, symbol) -> bool:
        ind = self.indicators[symbol]
        return all([ind["rsi"].is_ready, ind["bb"].is_ready])

    def _update_regime_multiplier(self) -> None:
        """Update position size multiplier based on market regime."""
        if not self.sma200.is_ready:
            self.regime_multiplier = 0.5  # Conservative when unknown
            return

        spy_price = self.securities[self.spy].price
        above_200dma = spy_price > self.sma200.current.value

        # {{REGIME_CONDITIONS}} - User-specified regime logic
        if above_200dma:
            self.regime_multiplier = 1.0  # Full size in uptrend
        else:
            self.regime_multiplier = 0.5  # Half size in downtrend

    def _entry_signal(self, symbol, data: Slice) -> bool:
        """RSI oversold entry (default mean reversion)"""
        ind = self.indicators[symbol]
        return ind["rsi"].current.value < 30

    def _exit_signal(self, symbol, data: Slice) -> bool:
        """RSI overbought or time exit"""
        ind = self.indicators[symbol]

        # RSI exit
        if ind["rsi"].current.value > 70:
            return True

        # Time exit
        if symbol in self.entry_bar:
            bars_held = self.time - self.entry_bar[symbol]
            if bars_held.days >= self.max_hold_bars:
                return True

        return False

    def _execute_entry(self, symbol, data: Slice) -> None:
        risk_dollars = self.portfolio.total_portfolio_value * self.risk_per_trade
        price = data[symbol].close
        stop_distance = price * 0.02  # 2% stop for mean reversion
        base_shares = int(risk_dollars / stop_distance)
        shares = int(base_shares * self.regime_multiplier)

        if shares > 0:
            self.market_order(symbol, shares)
            self.entry_bar[symbol] = self.time

    def _execute_exit(self, symbol, data: Slice) -> None:
        self.liquidate(symbol)
        self.entry_bar.pop(symbol, None)
