# region imports
from AlgorithmImports import *
# endregion

# ═══════════════════════════════════════════════════════════════════════════════
# HDD LOCKED PARAMETERS - DO NOT SWEEP
# ───────────────────────────────────────────────────────────────────────────────
# Trial: {{TRIAL_NUMBER}} of 5 | Hypothesis: {{HYPOTHESIS_ID}}
# Single Change This Trial: {{SINGLE_CHANGE}}
# Fail Condition: {{FAIL_CONDITION}}
# ═══════════════════════════════════════════════════════════════════════════════


class MomentumStrategy(QCAlgorithm):
    """
    Strategy Type: Momentum
    Template for trend-following strategies using breakouts and crossovers.
    Generated by: strategy-builder agent

    Placeholders:
    - {{STRATEGY_NAME}}: Strategy class name
    - {{SYMBOLS}}: List of symbols
    - {{ENTRY_CONDITIONS}}: Entry signal logic
    - {{EXIT_CONDITIONS}}: Exit signal logic
    - {{POSITION_SIZE}}: Sizing method
    """

    def initialize(self) -> None:
        # === Configuration ===
        self.set_start_date(2020, 1, 1)
        self.set_cash(100000)

        # === Universe ===
        self.symbols = []
        for ticker in {{SYMBOLS}}:
            self.symbols.append(self.add_equity(ticker, Resolution.DAILY).symbol)

        # === Indicators (Momentum) ===
        # HDD LOCKED: Do NOT sweep indicator periods
        self.indicators = {}
        for symbol in self.symbols:
            self.indicators[symbol] = {
                "ema_fast": self.ema(symbol, 20),
                "ema_slow": self.ema(symbol, 50),
                "atr": self.atr(symbol, 22),
                "donchian": self.dch(symbol, 20, 20),
            }

        # === Risk Parameters ===
        # HDD LOCKED: Risk parameter - requires new hypothesis to change
        self.risk_per_trade = 0.01
        self.max_positions = 5
        self.entry_prices = {}
        self.stops = {}

        # === Regime Detection ===
        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.sma200 = self.sma(self.spy, 200)
        self.regime_multiplier = 1.0  # Default, updated in on_data

    def on_data(self, data: Slice) -> None:
        self._update_regime_multiplier()

        for symbol in self.symbols:
            if not self._indicators_ready(symbol):
                continue

            if not self.portfolio[symbol].invested:
                if self._entry_signal(symbol, data):
                    self._execute_entry(symbol, data)
            else:
                if self._exit_signal(symbol, data):
                    self._execute_exit(symbol, data)

    def _update_regime_multiplier(self) -> None:
        """Update position size multiplier based on market regime."""
        if not self.sma200.is_ready:
            self.regime_multiplier = 0.5  # Conservative when unknown
            return

        spy_price = self.securities[self.spy].price
        above_200dma = spy_price > self.sma200.current.value

        # {{REGIME_CONDITIONS}} - User-specified regime logic
        if above_200dma:
            self.regime_multiplier = 1.0  # Full size in uptrend
        else:
            self.regime_multiplier = 0.5  # Half size in downtrend

    def _indicators_ready(self, symbol) -> bool:
        ind = self.indicators[symbol]
        return all(
            [ind["ema_fast"].is_ready, ind["ema_slow"].is_ready, ind["atr"].is_ready]
        )

    def _entry_signal(self, symbol, data: Slice) -> bool:
        """{{ENTRY_CONDITIONS}}"""
        ind = self.indicators[symbol]
        # EMA crossover (default momentum entry)
        return ind["ema_fast"].current.value > ind["ema_slow"].current.value

    def _exit_signal(self, symbol, data: Slice) -> bool:
        """{{EXIT_CONDITIONS}}"""
        # Chandelier stop (default momentum exit)
        if symbol in self.stops:
            return data[symbol].close < self.stops[symbol]
        return False

    def _execute_entry(self, symbol, data: Slice) -> None:
        """{{POSITION_SIZE}}"""
        price = data[symbol].close
        atr = self.indicators[symbol]["atr"].current.value
        stop_distance = atr * 3.0

        self.stops[symbol] = price - stop_distance
        risk_dollars = self.portfolio.total_portfolio_value * self.risk_per_trade
        base_shares = int(risk_dollars / stop_distance)
        shares = int(base_shares * self.regime_multiplier)

        if shares > 0:
            self.market_order(symbol, shares)
            self.entry_prices[symbol] = price

    def _execute_exit(self, symbol, data: Slice) -> None:
        self.liquidate(symbol)
        self.entry_prices.pop(symbol, None)
        self.stops.pop(symbol, None)
