# region imports
from AlgorithmImports import *
# endregion

# ═══════════════════════════════════════════════════════════════════════════════
# HDD LOCKED PARAMETERS - DO NOT SWEEP
# ───────────────────────────────────────────────────────────────────────────────
# Trial: {{TRIAL_NUMBER}} of 5 | Hypothesis: {{HYPOTHESIS_ID}}
# Single Change This Trial: {{SINGLE_CHANGE}}
# Fail Condition: {{FAIL_CONDITION}}
# ═══════════════════════════════════════════════════════════════════════════════


class MultiFactorStrategy(QCAlgorithm):
    """
    Strategy Type: Multi-Factor
    Template for combined signal strategies using multiple factors.
    Generated by: strategy-builder agent
    """

    def initialize(self) -> None:
        self.set_start_date(2020, 1, 1)
        self.set_cash(100000)

        # === Universe Selection ===
        self.universe_settings.resolution = Resolution.DAILY
        self.add_universe(self.coarse_selection)

        # === Factor Weights ===
        # HDD LOCKED: Do NOT sweep indicator periods
        self.factor_weights = {"momentum": 0.4, "value": 0.3, "quality": 0.3}

        # === Risk Parameters ===
        # HDD LOCKED: Risk parameter - requires new hypothesis to change
        self.max_holdings = 20
        self.rebalance_frequency = 21  # Trading days
        self.last_rebalance = None

        # === Regime Detection ===
        self.spy = self.add_equity("SPY", Resolution.DAILY).symbol
        self.sma200 = self.sma(self.spy, 200)
        self.regime_multiplier = 1.0  # Default, updated in on_data

    def coarse_selection(self, coarse):
        """Select liquid stocks"""
        sorted_by_volume = sorted(
            [x for x in coarse if x.has_fundamental_data and x.price > 5],
            key=lambda x: x.dollar_volume,
            reverse=True,
        )
        return [x.symbol for x in sorted_by_volume[:100]]

    def on_data(self, data: Slice) -> None:
        self._update_regime_multiplier()

        if self._should_rebalance():
            self._rebalance(data)

    def _should_rebalance(self) -> bool:
        if self.last_rebalance is None:
            return True
        days_since = (self.time - self.last_rebalance).days
        return days_since >= self.rebalance_frequency

    def _update_regime_multiplier(self) -> None:
        """Update position size multiplier based on market regime."""
        if not self.sma200.is_ready:
            self.regime_multiplier = 0.5  # Conservative when unknown
            return

        spy_price = self.securities[self.spy].price
        above_200dma = spy_price > self.sma200.current.value

        # {{REGIME_CONDITIONS}} - User-specified regime logic
        if above_200dma:
            self.regime_multiplier = 1.0  # Full size in uptrend
        else:
            self.regime_multiplier = 0.5  # Half size in downtrend

    def _calculate_factor_scores(self, data: Slice) -> dict:
        """Calculate composite factor scores"""
        scores = {}
        for symbol in self.active_securities.keys:
            if symbol in data:
                # Placeholder: implement actual factor calculations
                momentum_score = 0.5
                value_score = 0.5
                quality_score = 0.5

                composite = (
                    self.factor_weights["momentum"] * momentum_score
                    + self.factor_weights["value"] * value_score
                    + self.factor_weights["quality"] * quality_score
                )
                scores[symbol] = composite
        return scores

    def _rebalance(self, data: Slice) -> None:
        scores = self._calculate_factor_scores(data)

        # Rank and select top N
        ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
        targets = [symbol for symbol, score in ranked[: self.max_holdings]]

        # Equal weight positions with regime adjustment
        base_weight = 1.0 / self.max_holdings
        weight = base_weight * self.regime_multiplier

        # Liquidate positions not in targets
        for symbol in self.portfolio.keys:
            if self.portfolio[symbol].invested and symbol not in targets:
                self.liquidate(symbol)

        # Enter new positions
        for symbol in targets:
            if symbol in data:
                self.set_holdings(symbol, weight)

        self.last_rebalance = self.time
